#380 support multiple architectures for solver binaries z3
sosy-lab/java-smt pull request #395
Opened 2024-09-17 20:13 UTC by kfriedberger

2024-09-29 09:01 UTC, kfriedberger commented
This PR is currently blocked by https://github.com/sosy-lab/java-common-lib/pull/43

2024-09-29 21:14 UTC, kfriedberger commented
The current state seems to work as expected. I tested:
- publishing solver Z3 to Ivy and Maven, including x64 and arm64 for several operating systems (/)
- downloading from Ivy is backwards-compatible for Z3 (e.g., just increment the version of Z3). This works without changing the ivy-settings. We still nedd to find a way for publishing JavaSMT itself with a reasonable configuration.
- downloading from Maven requires more smaller changes. For example, as shown in this change: https://github.com/sosy-lab/java-smt/pull/395/commits/958dbc39b9498469dfe88b6a468b0bb188cabe03

Z3 is already published in Maven and Ivy, and works well with JavaSMT 5.0.1.
Feel free to test and give feedback.

As I do not have an ARM-based Apple machine available, maybe @ThomasHaas and @hernanponcedeleon can test whether it works as expected. Thanks.

2024-09-29 21:18 UTC, kfriedberger commented
If there is positive feedback, I will also publish Z3 in its latest version [4.13.2](https://github.com/Z3Prover/z3/releases) to Iva and Maven.

2024-10-03 13:21 UTC, ThomasHaas commented
It seems to work on ARM-based Macs now. Good job :)

2024-10-12 23:00 UTC, kfriedberger commented
Z3 was published to Ant/Ivy and Maven in versions 4.13.2 and 4.13.3.

There are some smaller issues that are currently blocking this PR from merging:
- JavaSMT uses outdated CI images for Linux, e.g., Z3 has removed support for Ubuntu 20.* and requires newwer GLIBC version. We will update the CI in another branch, before merging this PR.
- Z3 has a smaller regression when parsing formulas (due to a new feature that allows to compare formulas of incompatible types like Int/Bool): 
  https://github.com/Z3Prover/z3/issues/7419
  (our fix from 8e2f3b0b81c83f0bce649b06315536f0ac8c3caf might be changed/reverted in the future, if Z3 provides a bugfix)
- Z3 DLL on Windows x64 crashes:
  https://github.com/Z3Prover/z3/issues/7420

2024-10-20 10:40 UTC, kfriedberger commented
This branch is currently blocked by or waiting for:
- Z3 for Windows is broken on a default WIndows installation due to unexpected changes in msvcp140.dll. We need to wait for a new release of Z3 where this is fixed.
- MathSAT5 was compiled for newer GLIBC (Ubuntu 22.04) and does currently not work on Ubuntu 20.04 or older. This behaviour is similar to Z3, where support for Ubuntu 20.04 was dropped some weeks ago. However, we might want to re-compile the bindings with an older GLIBC.
- Gitlab-CI for ARM64 might be useful here, too.

2025-01-02 14:24 UTC, kfriedberger commented
I would like to have a preliminary review for these changes.

The following parts are work in progress and could be solved later:
- CI for ARM, for Linux, Windows, and also MacOS in general
- support more solvers on more architectures

2025-01-02 22:35 UTC, daniel-raffler reviewed
I've tried building the Z3 and Bitwuzla backends and everything seems to be working fine. Unfortunately I don't have any ARM system do  much more testing.

2025-01-02 22:35 UTC, daniel-raffler commented on doc/Developers-How-to-Release-into-Ivy.md
> +Finally, follow the instructions shown in the message at the end.
Would these steps work on windows/mac as well? Or is the idea to always use the docker image and then cross compile for all platforms from there? If so, we might want to make this more clear in the documentation.

2025-01-02 22:35 UTC, daniel-raffler commented on doc/Developers-How-to-Release-into-Ivy.md
> +for compiling the dependencies and assembling the libraries.
Maybe this paragraph from MathSAT could simple be moved further up?

2025-01-04 14:55 UTC, kfriedberger commented on build/build-publish-solvers/solver-bitwuzla.xml
> +    <property name="bitwuzla.buildForWindowsX64" value="true"/>
For testing single steps, having a property might be beneficial. For publication, one might always want all versions included. I would not remove the properties.

2025-01-04 14:56 UTC, kfriedberger commented on doc/Developers-How-to-Release-into-Ivy.md
> +Finally, follow the instructions shown in the message at the end.
Z3 is not compiled during these steps, but only packaged. We generate sources and JavaDoc for Java bindings and pack them, too. I wuld assume that these steps are independent of any platform or operating system and also work on Windows or MacOs.

2025-01-04 14:59 UTC, kfriedberger commented on doc/Developers-How-to-Release-into-Ivy.md
> +for compiling the dependencies and assembling the libraries.
Until now, we did not enforce any ordering of solvers in the documentation. One could apply alphabetical sorting as extra cleanup, possibly after this PR is merged.

2025-01-04 20:14 UTC, kfriedberger commented on build.xml
> +        <property name="libraryFiles" value="*.so *.dll *.dylib x64/*.so x64/*.dll x64/*.dylib arm64/*.so arm64/*.dll arm64/*.dylib"/>
I am unsure whether folders can be used in a 'fileset' attribute.

Currently, the folder structure is actually not optimal. We have the `root` directory for all architecture-independent or only x64-provided libraries and jars, and `x64` or `arm64` for specific libraries. It could be nicer to have an extra `dist` directory for everything we want to publish, with optional subdirectories for architecture.
Then we could simply remove `dist` completely.

2025-01-05 13:55 UTC, kfriedberger commented on build.xml
> +        <property name="libraryFiles" value="*.so *.dll *.dylib x64/*.so x64/*.dll x64/*.dylib arm64/*.so arm64/*.dll arm64/*.dylib"/>
With commit cd2529a68dafccc58a69f21d26f34ec04d96d349, we introduced a `dist` directory for solvers. This allows us to remove the directories `arm64` and `x64` and simplify the cleanup task.

2025-01-06 14:00 UTC, daniel-raffler commented on doc/Developers-How-to-Release-into-Ivy.md
> +Finally, follow the instructions shown in the message at the end.
Thanks for updating the documentation!

2025-01-19 19:45 UTC, kfriedberger commented
@daniel-raffler and @baierd : could you take a look and provide feedback? I would like to merge this PR in near time.

Beneigh Java-based solvers SMTInterpol and Princess, we now have 4 native solvers that are working on ARM64 platform: 
- with Linux on ARM64: Z3, MathSAT5, Bitwuzla, and OpenSMT.
- with Windows and MacOS on ARM64: Z3

The current changes to Ivy are backwards-compatible and allow to use and update existing JavaSMT integrations without further changes (such as in CPAchecker). If the user wants to use binary solvers for ARM64, he can modify his Ivy dependency to load the corresponding files. We already provide the corresponding files in Maven, so the user specify them via the pom-file..

2025-01-25 10:35 UTC, baierd requested changes
Overall very nice. I will test this PR on my Windows machine later today.

I have some small questions/suggestions, but did not find anything mayor.

2025-01-25 10:35 UTC, baierd commented on build/build-maven-publish.xml
> +        <stage-solver-file filename="libboolector" classifier="libboolector" fileending="so"/>
Maybe we should add the `x64` suffix for all existing solvers as well, so that we can discern their architecture more easily, and prepare adding ARM for more solvers. (Although we will most likely not support/get support for older solvers to be fair)

2025-01-25 10:35 UTC, baierd commented on src/org/sosy_lab/java_smt/test/SolverContextFactoryTest.java
> +  private String[] getRequiredLibcxx(String library) {
This is very nice!
We should add this information (and requirements in general) to the README.

2025-01-25 11:17 UTC, kfriedberger commented on build/build-maven-publish.xml
> +        <stage-solver-file filename="libbitwuzlaj" classifier="libbitwuzlaj-x64" filedirectory="${libDir.x64}" fileending="so"/>
While we can provide a backward-compatible version in Ivy/Ant, the same procedure was not implemented for Maven.

The difference is:
- Ivy needs to set a (global or project-dependent) artifact pattern, where an optional architecture flag is specified. See [build/build-ivy.xml L69](https://github.com/sosy-lab/java-smt/blob/13b3f1267994f33139ea906353eb3e08c532799c/build/build-ivy.xml#L69). If this is change not applied (also in other projects like CPAchecker), the developer will only access the x64-version of libraries.
- Maven allows to just add the architecture-flag directly: (example pom.xml)[https://github.com/sosy-lab/java-smt/blob/13b3f1267994f33139ea906353eb3e08c532799c/doc/Example-Maven-Project/pom.xml#L115], which makes it much simpler to update.

2025-01-25 11:21 UTC, kfriedberger commented on build/build-publish-solvers/macros.xml
> +                svn add repository/${ivy.organisation}/${ivy.module}/*-@{solverVersion}* repository/${ivy.organisation}/${ivy.module}/*/*-@{solverVersion}*
This line is correct, because we use additional directories `x64` and `arm64` for architecture-dependent files.

Examples:
- https://www.sosy-lab.org/ivy/org.sosy_lab/javasmt-solver-z3/arm64/
- https://www.sosy-lab.org/ivy/org.sosy_lab/javasmt-solver-z3/x64/

When publishing a solver for a specific architecture the first time, the line might even be insufficient, because SVN does not track contents in a new directory, if the directory itself is not tracked. I ignored this special case and just extended the command for the usual case, like updating an existing solver.

2025-01-25 11:26 UTC, kfriedberger commented on build/build-maven-publish.xml
> +        <stage-solver-file filename="libboolector" classifier="libboolector" fileending="so"/>
I though about this topic as well and would do the following:
- If there is a (sufficiently) new version of a solver, where we could provide multiple architectures or need to compile the new  library anyway, then update the Ivy and Maven configurations and scripts.
- Otherwise, keep current state.

I did this with OpenSMT in the last few commits in this PR. It was quite easy to compile it for ARM64 after refactoring the script and playing around with the GMP dependency. :smile:

2025-01-25 11:31 UTC, kfriedberger commented on src/org/sosy_lab/java_smt/test/SolverContextFactoryTest.java
> +  private String[] getRequiredLibcxx(String library) {
Good point. I will update the Linux-column in the README with this information.

Overall, we might think about dropping support for anything older than Ubuntu 22.04 (`GLIBC_2.33` and `GLIBCXX_3.4.26`), because the overhead in developement effort is quite high for quite few users.

2025-01-25 12:02 UTC, baierd commented on build/build-maven-publish.xml
> +        <stage-solver-file filename="libbitwuzlaj" classifier="libbitwuzlaj-x64" filedirectory="${libDir.x64}" fileending="so"/>
Thanks for the explanation!
We should add this to our guide for Maven.
Have you checked Gradle? Does it work like Maven?

2025-01-25 12:02 UTC, baierd commented on build/build-publish-solvers/macros.xml
> +                svn add repository/${ivy.organisation}/${ivy.module}/*-@{solverVersion}* repository/${ivy.organisation}/${ivy.module}/*/*-@{solverVersion}*
Ah i get it. Thanks!

2025-01-25 12:04 UTC, baierd commented on build/build-maven-publish.xml
> +        <stage-solver-file filename="libboolector" classifier="libboolector" fileending="so"/>
I agree with your assessment!
It's nice that apparently multiple solvers work with ARM64 rather easily.

2025-01-25 12:05 UTC, baierd commented on src/org/sosy_lab/java_smt/test/SolverContextFactoryTest.java
> +  private String[] getRequiredLibcxx(String library) {
Thank you!

I agree with that. Maybe we should release one more version with minimal changes, e.g. 5.1, and add all of the coming changes in a way that users can prepare.

2025-01-25 12:07 UTC, baierd commented
Something that might be worth a try is adding a static `info()` method that tries to read your OS and gives you information about available solvers, dependencies and requirements (e.g. copy the Windows binaries for a Dev build), or possibly even checks those requirements for you.

2025-01-25 13:41 UTC, kfriedberger commented
I would not expect such a info-feature from a library, but only in the main application.

2025-01-25 13:43 UTC, kfriedberger commented on build/build-maven-publish.xml
> +        <stage-solver-file filename="libbitwuzlaj" classifier="libbitwuzlaj-x64" filedirectory="${libDir.x64}" fileending="so"/>
Gradle is quite similar to Maven. I expect it to work.
I have not yet updated the Gradle files, but will do it soon.

2025-01-25 19:50 UTC, kfriedberger commented on build/build-maven-publish.xml
> +        <stage-solver-file filename="libbitwuzlaj" classifier="libbitwuzlaj-x64" filedirectory="${libDir.x64}" fileending="so"/>
Both, Maven and Gradle will depend on the latest release of JavaSMT to be included.
I updated the Maven examples with all newwest solvers, however, kept Gradle as-is for now. We need to update both after the merge and the corresponding release.

2025-01-25 20:01 UTC, kfriedberger commented
For executing and testing the ARM-based binaries, you can apply Podman/Docker with Qemu.
A corresponding Dockerfile would look like this:

```
FROM arm64v8/ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=UTC
ENV LANG=C.UTF-8

RUN apt-get update && apt-get install -y --no-install-recommends \
  wget curl \
  ant git \
  openjdk-17-jre-headless \
  openjdk-17-jdk-headless \
  libgomp1
```

Build with:

```
podman build --platform=linux/arm64 - < ubuntu2204-arm64.Dockerfile
```
The output will contain the ID in the last line.

Run with:
```
podman run -it \
    --mount type=bind,source=${HOME}/workspace,target=/workspace \
    --workdir /workspace/java-smt \
    ID
```

Podman/Docker with qemu is emulating ARM64 on x64 about 3-10 times slower than normal execution. I am thinking about an ARM-based CI, however Podman/Docker with Qemu might be too slow for that.

2025-01-25 20:03 UTC, kfriedberger commented on src/org/sosy_lab/java_smt/test/SolverContextFactoryTest.java
> +  private String[] getRequiredLibcxx(String library) {
Readme is updated now.

2025-01-25 22:54 UTC, baierd approved these changes
Looks good. Thanks for incorporating my suggestions! 

Do we want to document the Podman/Docker info in some file or issue?

2025-01-26 08:00 UTC, kfriedberger commented
The Podman/Docker file might be interesting for additional CI jobs. We will surely come across that topic in https://github.com/sosy-lab/java-smt/issues/384.

2025-01-26 08:02 UTC, merged